spring:
  application:
    name: crm
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
